# Site settings
author: Justin R. Zweifel
title: First Mile Struggles
header-img: img/home-bg.png
email: jzweifel15@yahoo.com
copyright_name: Justin R. Zweifel
description: > # this means to ignore newlines until "baseurl:"
  The start
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  Jzweifel15

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
